### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ebanDev** [kalliope-project/kalliope_neuron_openweathermap#10]
Hello, I have the following error when I try to run this module :

Exception in thread <class 'kalliope.signals.order.order.Order'>:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/signals/order/order.py", line 87, in run
    self.start_trigger()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 405, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 1092, in _process
    self._transition_queue[0]()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 423, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 433, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 283, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 294, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 140, in enter
    event_data.machine.callback(handle, event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.7.2-py3.7.egg/transitions/core.py", line 1037, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/signals/order/order.py", line 185, in analysing_order_thread
    is_api_call=False)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/SynapseLauncher.py", line 106, in run_matching_synapse_from_order
    execdata = lifo_buffer.execute(is_api_call=is_api_call)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 109, in execute
    self._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 139, in _process_synapse_list
    self._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/Lifo/LIFOBuffer.py", line 173, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/NeuronLauncher.py", line 62, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/NeuronLauncher.py", line 44, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "resources/neurons/openweathermap/openweathermap.py", line 84, in __init__
    self.say(returned_message)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/NeuronModule.py", line 152, in say
    tts_message = self._get_message_from_dict(message)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/NeuronModule.py", line 195, in _get_message_from_dict
    returned_message = self._get_say_template(self.say_template, message_dict)
  File "/usr/local/lib/python3.7/dist-packages/kalliope-0.6.0-py3.7.egg/kalliope/core/NeuronModule.py", line 209, in _get_say_template
    return t.render(**message_dict)
  File "/usr/local/lib/python3.7/dist-packages/Jinja2-3.0.0a1-py3.7.egg/jinja2/environment.py", line 1045, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/Jinja2-3.0.0a1-py3.7.egg/jinja2/environment.py", line 787, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/dist-packages/Jinja2-3.0.0a1-py3.7.egg/jinja2/environment.py", line 442, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute '11:00'

jinja2.exceptions.UndefinedError: 'dict object' has no attribute '11:00'

**Comment by ebanDev** [comment]
J'ai essayé en partant du template sur le site est ca marche ...
